# Makefile for prova

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=prova
SRCS=prova.c
BINDIR=/testbin
HOSTBINDIR=/hostbin

.include "$(TOP)/mk/os161.prog.mk"
.include "$(TOP)/mk/os161.hostprog.mk"

